/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105129;

// TODO: 01/06/20 logging
// TODO: 01/06/20 view

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

    }
}
